apiVersion: ENC[AES256_GCM,data:ZjE=,iv:w9w4UFO863j2IfKS4aiumUoQRxMBqO6s5rvrq3qcSfw=,tag:fVO7eJ+MeAeRfH0PZhlLQQ==,type:str]
kind: ENC[AES256_GCM,data:JWaghVW9,iv:PuWpjxA6JDsY+JIElRmWXb0/8c1wixSw54WluUCaB8k=,tag:Z2YpCa/gYYfPkvstZQs9xg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QoUj6eN5qLg=,iv:Tg1g0rfR2h5oMeruDOezZrrrMZfdIrQV4W2lWFjgxWs=,tag:l+KRtzewa2x1xReSdoLZ4w==,type:str]
type: ENC[AES256_GCM,data:9+EAuaQ9,iv:BmOO56x7lUE1YubPdu3SN1Mv4oz2fb4Sfjf/pCTKZDY=,tag:TwQ4SuWyCC13sYBJ4pSuog==,type:str]
data:
    key: ENC[AES256_GCM,data:1PQj0L8ZeqY=,iv:ktzxjjF08paQYr2DjgolxJw7XMLqvDPJMcDBtV+xS+c=,tag:nV03aWKVX8tdfTGuhVYH+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w8gjyxuw0e3dg7tguw7y2lccccsz05nw7n0fjdulv86e6a35aqssentt32
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MWs0ZkdlY0FrUHJCWHRs
            SWdYemhxSS9lZ3B0cFRhQllxYUVwMlBQOENNCklBOEJ1dElYRkMxbHo1WWRxN0RY
            emZ2Z1hiLzYyNmdWVGFrNlloeTRYNzQKLS0tIGIzSWR0WktpYjNMd2lSQ3JpNTY3
            L2pTVVg2K2JvNVpWTkNsdEFmc2lDazgKqA04t9X6JaCQY4UqHb9VsB5kY7jAxb3+
            efGR2Wem1uQjVVVZkMPYASKLbu4hrDdIrOuz/Hl01egpngrREwAL+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-19T12:48:10Z"
    mac: ENC[AES256_GCM,data:fdYM0N+n6wZHDMYuZW4pRmndtK48ODIM6qmQl6BSpCNEAG03LSkQozK/rsNMMGyFyKcFzC/4DE2e3JkVkIrEaLG6RjLr2LZZPFP3NSNh/SKecbH92sBuezjdkSRo9xZlFB4Kl1zoXZcVN2gCglJxg+e7b+X/n+SgHoM6NimfOFk=,iv:ocCniy2qNwMLMyRetlpnnkd6Tsk6OY55+rJYFtG7pyI=,tag:1fbOrjm0k/D5eIxNik2zmw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
